---
name: Create production build and autosubmit to playstore production track
on:
  push:
    branches:
      - main
    paths:
      - 'app.config.js'
      - 'app.json'
env:
  API_KEY: ${{ secrets.PROD_API_KEY }}
  PROJECT_ID: ${{ secrets.PROD_PROJECT_ID }}
  MESSAGING_SENDER_ID: ${{ secrets.PROD_MESSAGING_SENDER_ID }}
  APP_ID: ${{ secrets.PROD_APP_ID }}
  MEASUREMENT_ID: ${{ secrets.PROD_MEASUREMENT_ID }}
  AUTH_DOMAIN: ${{ secrets.PROD_PROJECT_ID }}.firebasedev.com
  DATABASE_URL: https://${{ secrets.PROD_PROJECT_ID }}.firebaseio.com/
  STORAGE_BUCKET: ${{ secrets.PROD_PROJECT_ID }}.appspot.com
jobs:
  build:
    name: Create build and submit
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Decode needed files
        run: |
          echo "${{ secrets.PROD_SERVICES_JSON }}" | base64 -d > google-services.json
          echo "${{ secrets.PROD_SERVICES_PLIST }}" | base64 -d > GoogleService-Info.plist
      - name: Set up Expo
        uses: expo/expo-github-action@v6
        with:
          eas-cache: true
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Create eas build
        run: eas build --profile production --platform android --non-interactive --auto-submit
